kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASS
    repo: ashokshingade24/caching-service
    tags:
      - latest
      - '1.0.1'
      - '1.0'
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: dev
